=== 0Charliecat/transitland-atlas/scripts/operator-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Transitland Atlas operator schema",
  "type": "object",
  "properties": {
    "onestop_id": {
      "type": "string"
    },
    "tags": {
      "type": "object",
      "properties": {
        "us_ntd_id": {
          "type": ["string", "array"]
        },
        "omd_provider_id": {
          "type": ["string", "array"]
        },
        "wikidata_id": {
          "type": ["string", "array"]
        }
      }
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": ["string", "null"]
    },
    "website": {
      "type": ["string", "null"]
    },
    "associated_feeds": {
      "type": "array"
    }
  }
}

=== 0Charliecat/transitland-atlas/operators/o-gc3cg-josephfoley.json
{
  "onestop_id": "o-gc3cg-josephfoley",
  "tags": {
    "agency_id": "593",
    "agency_lang": "EN"
  },
  "name": "Joseph Foley",
  "short_name": null,
  "website": "http://www.transportforireland.ie",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-gc3f-josephfoley~michaeldonegan"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-dr09-washingtoncountycommuter.json
{
  "onestop_id": "o-dr09-washingtoncountycommuter",
  "tags": {},
  "name": "Washington County Commuter",
  "short_name": null,
  "website": "http://www.washco-md.net/transit/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-dr09-washingtoncountycommuter",
      "gtfs_agency_id": "1"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-r3gj-pictonbuslines.json
{
  "onestop_id": "o-r3gj-pictonbuslines",
  "tags": {
    "agency_id": "74",
    "agency_lang": "EN",
    "agency_phone": "131500"
  },
  "name": "Picton Buslines",
  "short_name": null,
  "website": "http://transportnsw.info",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-r6-nswtrainlink~sydneytrains~buswayswesternsydney~interlinebus"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-rb03-yellocabs.json
{
  "onestop_id": "o-rb03-yellocabs",
  "tags": {},
  "name": "Yello Cabs",
  "short_name": null,
  "website": "https://www.intercity.co.nz/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-rb-atairporter380~manukauorangebus~tranzalpinerailway~abeltasm",
      "gtfs_agency_id": "YL"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-qskk-transhedland.json
{
  "onestop_id": "o-qskk-transhedland",
  "tags": {
    "agency_id": "27",
    "agency_lang": "en"
  },
  "name": "TransHedland",
  "short_name": null,
  "website": "http://www.pta.wa.gov.au/OurServices/RegionalTownBusServices/tabid/62/Default.aspx",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-q-transperth~transalbany~transbunbury~transbusselton~transgera"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-dhvk-manateecountyareatransit.json
{
  "onestop_id": "o-dhvk-manateecountyareatransit",
  "tags": {},
  "name": "Manatee County Area Transit",
  "short_name": null,
  "website": "http://www.mymanatee.org/home/government/departments/public-works/transit-paratransit.html",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-dhvk-manatee~fl~us",
      "gtfs_agency_id": "140"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-ud9d-esvil~reisidas.json
{
  "onestop_id": "o-ud9d-esvil~reisidas",
  "tags": {
    "agency_id": "804",
    "agency_lang": "et",
    "agency_phone": "+372 6004353"
  },
  "name": "Esvil-Reisid",
  "short_name": null,
  "website": "http://www.peatus.ee",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-ud-atkoliinidoÜ~aktsiaseltshansabussiliinid~kihnuveeteedas~väi"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-djz4-charlestonarearegionaltransportationauthority.json
{
  "onestop_id": "o-djz4-charlestonarearegionaltransportationauthority",
  "tags": {
    "agency_id": "213"
  },
  "name": "Charleston Area Regional Transportation Authority",
  "short_name": "CARTA",
  "website": "http://www.ridecarta.com/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-djz4-carta~sc~us"
    }
  ]
}
