=== 0Charliecat/transitland-atlas/scripts/operator-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Transitland Atlas operator schema",
  "type": "object",
  "properties": {
    "onestop_id": {
      "type": "string"
    },
    "tags": {
      "type": "object",
      "properties": {
        "us_ntd_id": {
          "type": ["string", "array"]
        },
        "omd_provider_id": {
          "type": ["string", "array"]
        },
        "wikidata_id": {
          "type": ["string", "array"]
        }
      }
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": ["string", "null"]
    },
    "website": {
      "type": ["string", "null"]
    },
    "associated_feeds": {
      "type": "array"
    }
  }
}

=== 0Charliecat/transitland-atlas/operators/o-9q-easternsierratransitauthority.json
{
  "onestop_id": "o-9q-easternsierratransitauthority",
  "tags": {
    "agency_id": "78",
    "agency_lang": "en",
    "agency_phone": "(800) 922-1930"
  },
  "name": "Eastern Sierra Transit Authority",
  "short_name": null,
  "website": "http://www.estransit.com/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-9q-easternsierra~ca~us"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-rb6-hanmerconnections.json
{
  "onestop_id": "o-rb6-hanmerconnections",
  "tags": {},
  "name": "Hanmer Connections",
  "short_name": null,
  "website": "https://www.intercity.co.nz/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-rb-atairporter380~manukauorangebus~tranzalpinerailway~abeltasm",
      "gtfs_agency_id": "HC"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-rbsm-valleyflyer.json
{
  "onestop_id": "o-rbsm-valleyflyer",
  "tags": {
    "agency_id": "VLYF",
    "agency_lang": "en",
    "agency_fare_url": "http://www.metlink.org.nz/tickets-and-fares/"
  },
  "name": "Valley Flyer",
  "short_name": null,
  "website": "http://www.metlink.org.nz",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-rbs-gowellington~tranzitcoachlines~paraparaumutaxisltd~kapitic"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-s-societàtrasportocerignola.json
{
  "onestop_id": "o-s-societàtrasportocerignola",
  "tags": {},
  "name": "Società Trasporto Cerignola",
  "short_name": "STC",
  "website": "http://www.comune.cerignola.fg.it/hh/index.php",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-s-societàtrasportocerignola",
      "gtfs_agency_id": "STC"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-dn5b-georgiatechtrolley~stingershuttles.json
{
  "onestop_id": "o-dn5b-georgiatechtrolley~stingershuttles",
  "tags": {
    "agency_id": "GATECH"
  },
  "name": "Georgia Tech Trolley & Stinger Shuttles",
  "short_name": null,
  "website": "https://pts.gatech.edu/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-dn5b-georgiatechtrolley~stingershuttles"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-gc-sercocaledoniansleeper.json
{
  "onestop_id": "o-gc-sercocaledoniansleeper",
  "tags": {
    "agency_id": "CS",
    "agency_lang": "en",
    "agency_phone": "0330 060 0500"
  },
  "name": "Caledonian Sleeper",
  "short_name": null,
  "website": "http://www.sleeper.scot/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-gc-arrivatrainswales~c2c~chilternrailways~crosscountry~eastcoa",
      "gtfs_agency_id": "CS"
    },
    {
      "feed_onestop_id": "f-gc-rail~delivery~group~planar~gtfs",
      "gtfs_agency_id": "CS"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-drk5-cttransit~newhaven.json
{
  "onestop_id": "o-drk5-cttransit~newhaven",
  "tags": {
    "us_ntd_id": "10055",
    "agency_lang": "en",
    "agency_phone": "203-624-0151"
  },
  "name": "CTTransit - New Haven",
  "short_name": null,
  "website": "http://www.cttransit.com",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-drk-cttransit~hartford"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-qe8f6-transcarnarvon.json
{
  "onestop_id": "o-qe8f6-transcarnarvon",
  "tags": {
    "agency_id": "26",
    "agency_lang": "en"
  },
  "name": "TransCarnarvon",
  "short_name": null,
  "website": "http://www.pta.wa.gov.au/OurServices/RegionalTownBusServices/tabid/62/Default.aspx",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-q-transperth~transalbany~transbunbury~transbusselton~transgera"
    }
  ]
}
