=== 0Charliecat/transitland-atlas/scripts/operator-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Transitland Atlas operator schema",
  "type": "object",
  "properties": {
    "onestop_id": {
      "type": "string"
    },
    "tags": {
      "type": "object",
      "properties": {
        "us_ntd_id": {
          "type": ["string", "array"]
        },
        "omd_provider_id": {
          "type": ["string", "array"]
        },
        "wikidata_id": {
          "type": ["string", "array"]
        }
      }
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": ["string", "null"]
    },
    "website": {
      "type": ["string", "null"]
    },
    "associated_feeds": {
      "type": "array"
    }
  }
}

=== 0Charliecat/transitland-atlas/operators/o-r1f9-adelaidemetroschoolservice~lightcitybuses.json
{
  "onestop_id": "o-r1f9-adelaidemetroschoolservice~lightcitybuses",
  "tags": {},
  "name": "Adelaide Metro - Light-City Buses School Service",
  "short_name": null,
  "website": "http://adelaidemetro.com.au/Timetables-Maps/Special-Services/School-Services",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-r1f-adelaidemetrocomau",
      "gtfs_agency_id": "71"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-f25-agencemtropolitainedetransport.json
{
  "onestop_id": "o-f25-agencemtropolitainedetransport",
  "tags": {
    "agency_id": "TRAINS",
    "agency_lang": "fr",
    "agency_fare_url": "https://www.amt.qc.ca/fr/titres-tarifs/titres-metropolitains"
  },
  "name": "Agence m√©tropolitaine de transport",
  "short_name": "AMT",
  "website": "http://www.amt.qc.ca/",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-f25d-agencemtropolitainedetransportexpress",
      "gtfs_agency_id": "EXPRESS"
    },
    {
      "feed_onestop_id": "f-f25-agencemtropolitainedetransport",
      "gtfs_agency_id": "TRAINS"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-gc0vy9-bereislandferries.json
{
  "onestop_id": "o-gc0vy9-bereislandferries",
  "tags": {},
  "name": "Bere Island Ferries",
  "short_name": null,
  "website": "http://www.bereislandferries.com",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-gc-donegalcoastalcruises~arranmorecar~passengerferryservice~ar",
      "gtfs_agency_id": "10009"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-rckq-metrolink.json
{
  "onestop_id": "o-rckq-metrolink",
  "tags": {},
  "name": "Metrolink",
  "short_name": null,
  "website": "http://www.aucklandtransport.govt.nz",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-rck-gowest~sealinkgroup~atairporter~atmetro~thepartybuscompany",
      "gtfs_agency_id": "NZBML"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-ezw5f-tuvisa~euskotran.json
{
  "onestop_id": "o-ezw5f-tuvisa~euskotran",
  "tags": {
    "agency_id": "TuvisaTran"
  },
  "name": "Tuvisa-EuskoTran",
  "short_name": null,
  "website": "http://www.vitoria-gasteiz.org/we001/was/we001Action.do?idioma=es&aplicacion=wb021&tabla=contenido&uid=65c21a87_117e9336274__7fba",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-ezw5f-tuvisa~euskotran"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-u30u-de~mitteldeutscher~verkehrsbund.json
{
  "onestop_id": "o-u30u-de~mitteldeutscher~verkehrsbund",
  "tags": {
    "agency_id": "LVTRAM",
    "agency_lang": "de"
  },
  "name": "Mitteldeutscher Verkehrsbund",
  "short_name": "MDV",
  "website": "http://www.mdv.de",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-u30u-de~leipziger~mitteldeutscher"
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-dpsc-detroitdepartmentoftransportation.json
{
  "onestop_id": "o-dpsc-detroitdepartmentoftransportation",
  "tags": {
    "us_ntd_id": "50119"
  },
  "name": "Detroit Department of Transportation",
  "short_name": "DDOT",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-dpsc-detroitdepartmentoftransportation",
      "gtfs_agency_id": ""
    }
  ]
}

=== 0Charliecat/transitland-atlas/operators/o-u3h4-mpkautobusy.json
{
  "onestop_id": "o-u3h4-mpkautobusy",
  "tags": {},
  "name": "MPK Autobusy",
  "short_name": null,
  "website": "http://www.mpk.wroc.pl",
  "associated_feeds": [
    {
      "feed_onestop_id": "f-u3h4-mpkautobusy~mpktramwaje~dla~sevibussiechnice~dlawiszniama",
      "gtfs_agency_id": "2"
    }
  ]
}
